### ISSUE TITLE
script trouble

### ISSUE THREAD

**Issue by nhpackard** [polyworld/polyworld#19]
Hi,
Polyworld newbie here.
Having trouble to get the scripts to work. e.g.:
* dorun.sh is calling Polyworld with no argument, when Polyworld wants a world file.
* trial.py is looking for a wf named trial.wf, which is nowhere to be found.  Maybe I just use anything, like hello.wf?

Also, very interested in getting all those diag windows present in various screen shots.  Any doc pointers for those?

**Comment by larryy** [comment]
Not all, possibly most, of those scripts are not intended to be used directly, but are there to support other scripts. I'm sure it could be better organized and much better documented.

In addition to the Polyworld Wiki on GitHub (linked from the source base on GitHub), there are a few interesting docs in the polyworld/docs directory. Particularly proplib.odt and pwfarm.odt. Though if one is diving into details of the neural topologies and dynamics, some of the other .txt docs may be useful.

It's been a while since I used them now, but the pwfarm scripts, mostly by Sean Dougherty, were our primary way of doing large-scale parallel simulations on multiple machines. We would typically use pwfarm to launch 10 simulations (or 20 if doing both passive and driven runs) across 10 machines.

But for individual runs you can just run ./polyworld <worldfile> and you're good.

It looks to me like dorun.sh takes one argument, which is the worldfile. I don't know why it's letting you invoke it without an argument.

I don't remember trial.py. Based on age and blame, I believe Sean added that, and it was an experiment to be able to run Polyworld with special hand-crafted seed genomes. I suspect trial.wf just got lost somewhere along the way, but trial.py was not used for any of the published work.

I communicated with you in email about the windows, but FTR, at least when you're running Polyworld on a Mac, you should be able to bring those other windows up by just selecting them in the "Windows" menu. It's not bundled like a proper Mac app, but thanks to Qt, should otherwise behave as one.

**Comment by nhpackard** [comment]
Ah! On my build, it appears to be the `View` menu.  All the additional windows are accessible there.

I saw the pwfarm.odt.  I will try and extract info for making simpler non-farm runs from there.

`dorun.sh` takes an arg, but it is a tag for the run directory, not a wf.  I'll just fix a version to pass in the worldfile as well....

I'm guessing that `dorun.sh` was an untested afterthought, sort of like `trial.py`.  I will look to the workhorse farm scripts, as documented in `pwfarm.odt`.
